service: aws-node-http-api-project
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-3

functions:
  api:
    handler: src/hello.handler
    events:
      - httpApi:
          path: /
          method: get
resources:
  Resources:
    TodoTable:
      Type: AWS::DynamoDB::Table
      Properties: TodoTable
 

